### ISSUE TITLE
Why is the LRU item removed from the head and not the tail?

### ISSUE THREAD

**Issue by halpz** [nicklockwood/LRUCache#9]
should the head and tail property names be switched here?

**Comment by halpz** [comment]
I thought items should be added to the head and removed from the tail?

**Comment by halpz** [comment]
```
// Append container to list (must be called inside lock)
    func append(_ container: Container) {
        assert(container.prev == nil)
        if tail == nil {
            tail = container
        }
        container.next = head
        head?.next = container
        head = container
    }

    // Remove expired values (must be called outside lock)
    func clean() {
        lock.lock()
        defer { lock.unlock() }
        while totalCost > totalCostLimit || count > countLimit,
              let container = tail
        {
            remove(container)
            values.removeValue(forKey: container.key)
            totalCost -= container.cost
        }
    }
```

and setting container.prev = nil at the end of the remove function

**Comment by nicklockwood** [comment]
I'm not sure if you're reporting a bug or just a code style issue? As far as I can tell, the current behavior is correct. Head represents the oldest item in the list and tail is the newest. Items are inserted at the tail (newest) end and removed from the head (oldest) end.

If I make the changes you proposed, the unit tests get stuck in an infinite loop due to allValues never terminating. If I fix that, the remove() function crashes, and so on.

If you're just talking about a stylistic issue, the implementation here is a double-linked list, so AFAIK there's no convention that says you should only insert at the head of a list, and the term "append" implies insertion at the end.

You have drawn my attention to the fact that "head" and "tail" are rather meaningless in this context however, and "oldest" and "newest" would probably be better property names.

**Comment by halpz** [comment]
yeah sorry I was just confused by the semantics, the code works perfectly - I assumed that items always go from head to tail so it threw me off
